// AUTO-GENERATED by scripts/gen-catalog.mjs from the Printify shop.
// Editable, but re-running the script overwrites it with fresh variant ids + mockups.
//
// SINGLE SOURCE OF TRUTH: products -> colors -> sizes -> Printify variant ids.

export type Size = "S" | "M" | "L" | "XL" | "XXL" | "3XL" | "4XL";
export const SIZE_ORDER: Size[] = ["S","M","L","XL","XXL","3XL","4XL"];

export interface ColorVariant {
  name: string;
  swatch: string; // hex for the picker
  images: string[]; // ordered mockups: front, on-person, lifestyle, back
  image?: string; // legacy first image (hero/feed compat) = images[0]
  variants: Partial<Record<Size, number>>; // size -> Printify variant id
}

export interface Product {
  name: string;
  priceCents: number;
  tagline?: string;
  blurb?: string;
  printifyProductId: string;
  colors: ColorVariant[];
}

export const CATALOG: Record<string, Product> = {
  "knicks-in-four": {
    "name": "Knicks in Four Tee",
    "priceCents": 3999,
    "tagline": "THE FINALS DROP",
    "blurb": "The whole city is saying it, so we put it on a shirt. Heavyweight Comfort Colors cotton, shipped from New Jersey.",
    "printifyProductId": "6a27897a8f2246d09f0acb65",
    "colors": [
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79169,
          "S": 73199,
          "M": 73203,
          "XL": 73211,
          "L": 73207,
          "XXL": 73215,
          "4XL": 101476
        }
      },
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79114,
          "L": 73204,
          "XL": 73208,
          "M": 73200,
          "S": 73196,
          "XXL": 73212,
          "4XL": 101423
        }
      },
      {
        "name": "Graphite",
        "swatch": "#4f5356",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79135,
          "M": 78962,
          "XL": 78964,
          "S": 78961,
          "L": 78963,
          "XXL": 78965,
          "4XL": 101443
        }
      },
      {
        "name": "Grey",
        "swatch": "#b9bbbb",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79137,
          "L": 78973,
          "M": 78972,
          "XL": 78974,
          "S": 78971,
          "XXL": 78975,
          "4XL": 101445
        }
      },
      {
        "name": "Granite",
        "swatch": "#9b9a94",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79133,
          "L": 73982,
          "XL": 73989,
          "S": 73968,
          "M": 73975,
          "XXL": 73996,
          "4XL": 101441
        }
      },
      {
        "name": "Mystic Blue",
        "swatch": "#5f7e93",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79151,
          "L": 79033,
          "S": 79031,
          "XL": 79034,
          "M": 79032,
          "XXL": 79035,
          "4XL": 101459
        }
      }
    ]
  },
  "better-than-brunson": {
    "name": "Better Than Brunson Tee",
    "priceCents": 3999,
    "tagline": "CAPTAIN CLUTCH",
    "blurb": "Everyone's better than Jalen Brunson — until it's time to be better than Jalen Brunson. For the doubters and the believers.",
    "printifyProductId": "6a27c36891cf9037720216b7",
    "colors": [
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79169,
          "S": 73199,
          "M": 73203,
          "XL": 73211,
          "L": 73207,
          "XXL": 73215,
          "4XL": 101476
        }
      },
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79114,
          "L": 73204,
          "XL": 73208,
          "M": 73200,
          "S": 73196,
          "XXL": 73212,
          "4XL": 101423
        }
      },
      {
        "name": "Graphite",
        "swatch": "#4f5356",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79135,
          "M": 78962,
          "XL": 78964,
          "S": 78961,
          "L": 78963,
          "XXL": 78965,
          "4XL": 101443
        }
      },
      {
        "name": "Grey",
        "swatch": "#b9bbbb",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79137,
          "L": 78973,
          "M": 78972,
          "XL": 78974,
          "S": 78971,
          "XXL": 78975,
          "4XL": 101445
        }
      },
      {
        "name": "Granite",
        "swatch": "#9b9a94",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79133,
          "L": 73982,
          "XL": 73989,
          "S": 73968,
          "M": 73975,
          "XXL": 73996,
          "4XL": 101441
        }
      },
      {
        "name": "Mystic Blue",
        "swatch": "#5f7e93",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/126095/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/98446/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79151,
          "L": 79033,
          "S": 79031,
          "XL": 79034,
          "M": 79032,
          "XXL": 79035,
          "4XL": 101459
        }
      }
    ]
  },
  "corgi-wrong": {
    "name": "Corgi's Gonna Be Wrong Tee",
    "priceCents": 3999,
    "tagline": "FADE THE DOG",
    "blurb": "The corgi's gonna be wrongggg. For everyone who fades the playoff pet picks and rides with New York.",
    "printifyProductId": "6a27c372cf9078f4a3052270",
    "colors": [
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/112433/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/100630/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/100637/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/98446/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79169,
          "S": 73199,
          "M": 73203,
          "XL": 73211,
          "L": 73207,
          "XXL": 73215,
          "4XL": 101476
        }
      },
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/112433/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/100630/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/100637/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/98446/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79114,
          "L": 73204,
          "XL": 73208,
          "M": 73200,
          "S": 73196,
          "XXL": 73212,
          "4XL": 101423
        }
      },
      {
        "name": "Graphite",
        "swatch": "#4f5356",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/112433/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/100630/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/100637/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/98446/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79135,
          "M": 78962,
          "XL": 78964,
          "S": 78961,
          "L": 78963,
          "XXL": 78965,
          "4XL": 101443
        }
      },
      {
        "name": "Grey",
        "swatch": "#b9bbbb",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/112433/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/100630/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/100637/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/98446/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79137,
          "L": 78973,
          "M": 78972,
          "XL": 78974,
          "S": 78971,
          "XXL": 78975,
          "4XL": 101445
        }
      },
      {
        "name": "Granite",
        "swatch": "#9b9a94",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/112433/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/100630/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/100637/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/98446/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79133,
          "L": 73982,
          "XL": 73989,
          "S": 73968,
          "M": 73975,
          "XXL": 73996,
          "4XL": 101441
        }
      },
      {
        "name": "Mystic Blue",
        "swatch": "#5f7e93",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/112433/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/100630/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/100637/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/98446/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=back"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79151,
          "L": 79033,
          "S": 79031,
          "XL": 79034,
          "M": 79032,
          "XXL": 79035,
          "4XL": 101459
        }
      }
    ]
  }
};

export interface ResolvedLine {
  name: string;
  priceCents: number;
  item: { product_id: string; variant_id: number; quantity: 1 };
}

/** Resolve { productId, color, size } to a priced line + Printify item. Throws on any miss. */
export function resolveLine(productId: string, color: string, size: Size): ResolvedLine {
  const product = CATALOG[productId];
  if (!product) throw new Error(`Unknown product: ${productId}`);
  const c = product.colors.find((x) => x.name === color);
  if (!c) throw new Error(`Unknown color ${color} for ${productId}`);
  const variant_id = c.variants[size];
  if (variant_id === undefined) throw new Error(`Unknown size ${size} for ${productId} / ${color}`);
  return {
    name: `${product.name} — ${color} / ${size}`,
    priceCents: product.priceCents,
    item: { product_id: product.printifyProductId, variant_id, quantity: 1 },
  };
}

export function listProducts(): Array<Product & { id: string }> {
  return Object.entries(CATALOG).map(([id, product]) => ({ id, ...product }));
}
