// AUTO-GENERATED by scripts/gen-catalog.mjs from the Printify shop.
// Editable, but re-running the script overwrites it with fresh variant ids + mockups.
//
// SINGLE SOURCE OF TRUTH: products -> colors -> sizes -> Printify variant ids.

export type Size = "S" | "M" | "L" | "XL" | "XXL" | "3XL";
export const SIZE_ORDER: Size[] = ["S","M","L","XL","XXL","3XL"];

export interface ColorVariant {
  name: string;
  swatch: string; // hex for the picker
  images: string[]; // ordered mockups: front, on-person, lifestyle — back views excluded (blank shirts)
  image?: string; // legacy first image (hero/feed compat) = images[0]
  variants: Partial<Record<Size, number>>; // size -> Printify variant id
}

export interface Product {
  name: string;
  priceCents: number; // the CHARGED price (sale price while a sale is active)
  compareAtCents?: number; // anchor/list price for display only — never charged
  tagline?: string;
  blurb?: string;
  printifyProductId: string;
  colors: ColorVariant[];
}

export const CATALOG: Record<string, Product> = {
  "knicks-in-four": {
    "name": "Knicks in Four Tee",
    "priceCents": 3999,
    "tagline": "MY MAYOR MUSLIM",
    "blurb": "The whole city is saying it, so we put it on a shirt. Heavyweight Comfort Colors cotton, shipped from New Jersey.",
    "printifyProductId": "6a27897a8f2246d09f0acb65",
    "colors": [
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/100674/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79114,
          "L": 73204,
          "XL": 73208,
          "M": 73200,
          "S": 73196,
          "XXL": 73212
        }
      },
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/100674/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79169,
          "S": 73199,
          "M": 73203,
          "XL": 73211,
          "L": 73207,
          "XXL": 73215
        }
      },
      {
        "name": "Graphite",
        "swatch": "#4f5356",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/100674/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79135,
          "M": 78962,
          "XL": 78964,
          "S": 78961,
          "L": 78963,
          "XXL": 78965
        }
      },
      {
        "name": "Grey",
        "swatch": "#b9bbbb",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/100674/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79137,
          "L": 78973,
          "M": 78972,
          "XL": 78974,
          "S": 78971,
          "XXL": 78975
        }
      },
      {
        "name": "Granite",
        "swatch": "#9b9a94",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/100674/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79133,
          "L": 73982,
          "XL": 73989,
          "S": 73968,
          "M": 73975,
          "XXL": 73996
        }
      },
      {
        "name": "Mystic Blue",
        "swatch": "#5f7e93",
        "images": [
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/112433/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/100630/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-front",
          "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/100674/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-3-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27897a8f2246d09f0acb65/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79151,
          "L": 79033,
          "S": 79031,
          "XL": 79034,
          "M": 79032,
          "XXL": 79035
        }
      }
    ]
  },
  "popes-on-our-side": {
    "name": "Pope's on Our Side Tee",
    "priceCents": 3999,
    "tagline": "POPE'S ON OUR SIDE",
    "blurb": "My Mayor Muslim, my bagels Jewish, the Pope's on our side — divine intervention says Knicks in 5. Soft cotton tee, shipped free from New Jersey in 2–3 days.",
    "printifyProductId": "6a2d9a0173ad2eacae0ee154",
    "colors": [
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38191/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38191/100616/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38191/100619/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38191/127673/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38191/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
        "variants": {
          "L": 38191,
          "XL": 38205,
          "S": 38163,
          "M": 38177,
          "3XL": 42120,
          "XXL": 38219
        }
      },
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38192/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38192/100616/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38192/100619/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38192/127673/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38192/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
        "variants": {
          "XL": 38206,
          "L": 38192,
          "M": 38178,
          "S": 38164,
          "3XL": 42122,
          "XXL": 38220
        }
      },
      {
        "name": "Royal",
        "swatch": "#1c4d92",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38189/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38189/100616/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38189/100619/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38189/127673/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38189/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
        "variants": {
          "S": 38161,
          "XL": 38203,
          "L": 38189,
          "M": 38175,
          "3XL": 42118,
          "XXL": 38217
        }
      },
      {
        "name": "Orange",
        "swatch": "#e3592a",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/42802/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/42802/100616/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/42802/100619/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/42802/127673/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/42802/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
        "variants": {
          "S": 42796,
          "M": 42799,
          "L": 42802,
          "XL": 42805,
          "3XL": 42811,
          "XXL": 42808
        }
      },
      {
        "name": "Charcoal",
        "swatch": "#565459",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38181/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38181/100616/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38181/100619/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38181/127673/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/38181/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
        "variants": {
          "S": 38153,
          "M": 38167,
          "XL": 38195,
          "L": 38181,
          "3XL": 42109,
          "XXL": 38209
        }
      },
      {
        "name": "Ice Grey",
        "swatch": "#cfcecc",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/66243/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/66243/100616/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/66243/100619/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/66243/127673/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9a0173ad2eacae0ee154/66243/97992/my-mayor-muslim-my-bagels-jewish-my-bagels-jewish-t-shirt-knicks-in-5-tee.jpg?camera_label=front",
        "variants": {
          "XL": 66244,
          "L": 66243,
          "S": 66241,
          "M": 66242,
          "3XL": 66246,
          "XXL": 66245
        }
      }
    ]
  },
  "saturday-night-live": {
    "name": "Saturday Night Live Tee",
    "priceCents": 3999,
    "tagline": "MY SATURDAY NIGHT LIVE",
    "blurb": "My Mayor Muslim, my bagels Jewish, my Saturday Night Live — the full New York starter pack, Knicks in 5. Soft cotton tee, shipped free from New Jersey in 2–3 days.",
    "printifyProductId": "6a2d9b4064e16026a6060e28",
    "colors": [
      {
        "name": "Royal",
        "swatch": "#1c4d92",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38189/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38189/100616/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38189/100619/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38189/127673/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38189/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
        "variants": {
          "S": 38161,
          "XL": 38203,
          "L": 38189,
          "M": 38175,
          "3XL": 42118,
          "XXL": 38217
        }
      },
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38191/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38191/100616/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38191/100619/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38191/127673/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38191/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
        "variants": {
          "L": 38191,
          "XL": 38205,
          "S": 38163,
          "M": 38177,
          "3XL": 42120,
          "XXL": 38219
        }
      },
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38192/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38192/100616/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38192/100619/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38192/127673/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38192/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
        "variants": {
          "XL": 38206,
          "L": 38192,
          "M": 38178,
          "S": 38164,
          "3XL": 42122,
          "XXL": 38220
        }
      },
      {
        "name": "Orange",
        "swatch": "#e3592a",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/42802/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/42802/100616/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/42802/100619/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/42802/127673/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/42802/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
        "variants": {
          "S": 42796,
          "M": 42799,
          "L": 42802,
          "XL": 42805,
          "3XL": 42811,
          "XXL": 42808
        }
      },
      {
        "name": "Charcoal",
        "swatch": "#565459",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38181/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38181/100616/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38181/100619/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38181/127673/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/38181/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
        "variants": {
          "S": 38153,
          "M": 38167,
          "XL": 38195,
          "L": 38181,
          "3XL": 42109,
          "XXL": 38209
        }
      },
      {
        "name": "Ice Grey",
        "swatch": "#cfcecc",
        "images": [
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/66243/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/66243/100616/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/66243/100619/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/66243/127673/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a2d9b4064e16026a6060e28/66243/97992/my-mayor-muslim-my-bagels-jewish-t-shirt-sat-night-live-knicks-in-5.jpg?camera_label=front",
        "variants": {
          "XL": 66244,
          "L": 66243,
          "S": 66241,
          "M": 66242,
          "3XL": 66246,
          "XXL": 66245
        }
      }
    ]
  },
  "knicks-in-five": {
    "name": "Knicks in Five Tee",
    "priceCents": 3999,
    "tagline": "TRUMP KILLED THE VIBES",
    "blurb": "The whole bit, updated for Game 5 — My Mayor Muslim, My Bagels Jewish, and Trump killed the vibes. Soft cotton tee, shipped free from New Jersey in 2–3 days.",
    "printifyProductId": "6a29fb43b68139813c06d632",
    "colors": [
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38192/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38192/100616/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38192/100619/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38192/127673/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38192/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
        "variants": {
          "XL": 38206,
          "L": 38192,
          "M": 38178,
          "S": 38164,
          "3XL": 42122,
          "XXL": 38220
        }
      },
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38191/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38191/100616/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38191/100619/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38191/127673/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38191/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
        "variants": {
          "L": 38191,
          "XL": 38205,
          "S": 38163,
          "M": 38177,
          "3XL": 42120,
          "XXL": 38219
        }
      },
      {
        "name": "Royal",
        "swatch": "#1c4d92",
        "images": [
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38189/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38189/100616/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38189/100619/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38189/127673/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38189/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
        "variants": {
          "S": 38161,
          "XL": 38203,
          "L": 38189,
          "M": 38175,
          "3XL": 42118,
          "XXL": 38217
        }
      },
      {
        "name": "Orange",
        "swatch": "#e3592a",
        "images": [
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/42802/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/42802/100616/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/42802/100619/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/42802/127673/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/42802/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
        "variants": {
          "S": 42796,
          "M": 42799,
          "L": 42802,
          "XL": 42805,
          "3XL": 42811,
          "XXL": 42808
        }
      },
      {
        "name": "Charcoal",
        "swatch": "#565459",
        "images": [
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38181/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38181/100616/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38181/100619/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38181/127673/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/38181/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
        "variants": {
          "S": 38153,
          "M": 38167,
          "XL": 38195,
          "L": 38181,
          "3XL": 42109,
          "XXL": 38209
        }
      },
      {
        "name": "Ice Grey",
        "swatch": "#cfcecc",
        "images": [
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/66243/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/66243/100616/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/66243/100619/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/66243/127673/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fb43b68139813c06d632/66243/97992/knicks-in-5-t-shirt-knicks-basketball-tee-orange-moon-x-design.jpg?camera_label=front",
        "variants": {
          "XL": 66244,
          "L": 66243,
          "S": 66241,
          "M": 66242,
          "3XL": 66246,
          "XXL": 66245
        }
      }
    ]
  },
  "cream-cheese-chive": {
    "name": "Cream Cheese Chive Tee",
    "priceCents": 3999,
    "tagline": "MY CREAM CHEESE CHIVE",
    "blurb": "My Mayor Muslim, my bagels Jewish, my cream cheese chive — the full New York order, Knicks in 5. Soft cotton tee, shipped free from New Jersey in 2–3 days.",
    "printifyProductId": "6a29fcb2fe6ec8a6d110b144",
    "colors": [
      {
        "name": "Ice Grey",
        "swatch": "#cfcecc",
        "images": [
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/66243/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/66243/100616/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/66243/100619/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/66243/127673/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/66243/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
        "variants": {
          "XL": 66244,
          "L": 66243,
          "S": 66241,
          "M": 66242,
          "3XL": 66246,
          "XXL": 66245
        }
      },
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38191/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38191/100616/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38191/100619/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38191/127673/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38191/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
        "variants": {
          "L": 38191,
          "XL": 38205,
          "S": 38163,
          "M": 38177,
          "3XL": 42120,
          "XXL": 38219
        }
      },
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38192/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38192/100616/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38192/100619/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38192/127673/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38192/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
        "variants": {
          "XL": 38206,
          "L": 38192,
          "M": 38178,
          "S": 38164,
          "3XL": 42122,
          "XXL": 38220
        }
      },
      {
        "name": "Royal",
        "swatch": "#1c4d92",
        "images": [
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38189/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38189/100616/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38189/100619/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38189/127673/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38189/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
        "variants": {
          "S": 38161,
          "XL": 38203,
          "L": 38189,
          "M": 38175,
          "3XL": 42118,
          "XXL": 38217
        }
      },
      {
        "name": "Orange",
        "swatch": "#e3592a",
        "images": [
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/42802/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/42802/100616/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/42802/100619/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/42802/127673/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/42802/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
        "variants": {
          "S": 42796,
          "M": 42799,
          "L": 42802,
          "XL": 42805,
          "3XL": 42811,
          "XXL": 42808
        }
      },
      {
        "name": "Charcoal",
        "swatch": "#565459",
        "images": [
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38181/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38181/100616/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38181/100619/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=person-2-front",
          "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38181/127673/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=lifestyle"
        ],
        "image": "https://images-api.printify.com/mockup/6a29fcb2fe6ec8a6d110b144/38181/97992/my-mayor-muslim-my-bagels-jewish-my-cream-cheese-chive-t-shirt.jpg?camera_label=front",
        "variants": {
          "S": 38153,
          "M": 38167,
          "XL": 38195,
          "L": 38181,
          "3XL": 42109,
          "XXL": 38209
        }
      }
    ]
  },
  "better-than-brunson": {
    "name": "Better Than Brunson Tee",
    "priceCents": 3999,
    "tagline": "CAPTAIN CLUTCH",
    "blurb": "Everyone's better than Jalen Brunson — until it's time to be better than Jalen Brunson. For the doubters and the believers.",
    "printifyProductId": "6a27c36891cf9037720216b7",
    "colors": [
      {
        "name": "Grey",
        "swatch": "#b9bbbb",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/98448/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/100634/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78973/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79137,
          "L": 78973,
          "M": 78972,
          "XL": 78974,
          "S": 78971,
          "XXL": 78975
        }
      },
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/98448/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/100634/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73207/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79169,
          "S": 73199,
          "M": 73203,
          "XL": 73211,
          "L": 73207,
          "XXL": 73215
        }
      },
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/98448/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/100634/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73204/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79114,
          "L": 73204,
          "XL": 73208,
          "M": 73200,
          "S": 73196,
          "XXL": 73212
        }
      },
      {
        "name": "Graphite",
        "swatch": "#4f5356",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/98448/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/100634/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/78963/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79135,
          "M": 78962,
          "XL": 78964,
          "S": 78961,
          "L": 78963,
          "XXL": 78965
        }
      },
      {
        "name": "Granite",
        "swatch": "#9b9a94",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/98448/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/100634/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/73982/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79133,
          "L": 73982,
          "XL": 73989,
          "S": 73968,
          "M": 73975,
          "XXL": 73996
        }
      },
      {
        "name": "Mystic Blue",
        "swatch": "#5f7e93",
        "images": [
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/98448/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/100634/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-front",
          "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/100637/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-4-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c36891cf9037720216b7/79033/98445/my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79151,
          "L": 79033,
          "S": 79031,
          "XL": 79034,
          "M": 79032,
          "XXL": 79035
        }
      }
    ]
  },
  "corgi-wrong": {
    "name": "Corgi's Gonna Be Wrong Tee",
    "priceCents": 3999,
    "tagline": "FADE THE CORGI",
    "blurb": "The corgi's gonna be wrongggg. For everyone who fades the playoff pet picks and rides with New York.",
    "printifyProductId": "6a27c372cf9078f4a3052270",
    "colors": [
      {
        "name": "Black",
        "swatch": "#1c1c1c",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/126111/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context-2",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/100629/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=folded"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73204/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79114,
          "L": 73204,
          "XL": 73208,
          "M": 73200,
          "S": 73196,
          "XXL": 73212
        }
      },
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/126111/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context-2",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/100629/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=folded"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73207/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79169,
          "S": 73199,
          "M": 73203,
          "XL": 73211,
          "L": 73207,
          "XXL": 73215
        }
      },
      {
        "name": "Graphite",
        "swatch": "#4f5356",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/126111/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context-2",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/100629/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=folded"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78963/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79135,
          "M": 78962,
          "XL": 78964,
          "S": 78961,
          "L": 78963,
          "XXL": 78965
        }
      },
      {
        "name": "Grey",
        "swatch": "#b9bbbb",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/126111/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context-2",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/100629/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=folded"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/78973/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79137,
          "L": 78973,
          "M": 78972,
          "XL": 78974,
          "S": 78971,
          "XXL": 78975
        }
      },
      {
        "name": "Granite",
        "swatch": "#9b9a94",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/126111/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context-2",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/100629/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=folded"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/73982/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79133,
          "L": 73982,
          "XL": 73989,
          "S": 73968,
          "M": 73975,
          "XXL": 73996
        }
      },
      {
        "name": "Mystic Blue",
        "swatch": "#5f7e93",
        "images": [
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/126095/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/126111/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=person-5-context-2",
          "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/100629/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=folded"
        ],
        "image": "https://images-api.printify.com/mockup/6a27c372cf9078f4a3052270/79033/98445/copy-of-my-mayor-muslim-knicks-in-four-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79151,
          "L": 79033,
          "S": 79031,
          "XL": 79034,
          "M": 79032,
          "XXL": 79035
        }
      }
    ]
  },
  "he-is-my-everything": {
    "name": "He Is My Everything Tee",
    "priceCents": 3999,
    "tagline": "HE IS MY FATHER",
    "blurb": "Doctor, engineer, pastor, father — he's the whole résumé, and we only needed him to hit the corner three. Heavyweight Comfort Colors cotton, shipped fresh out of New Jersey.",
    "printifyProductId": "6a27dd8575aae553c70ecf64",
    "colors": [
      {
        "name": "Grey",
        "swatch": "#b9bbbb",
        "images": [
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/78973/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/78973/112433/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/78973/98448/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/78973/126095/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-5-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/78973/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79137,
          "L": 78973,
          "M": 78972,
          "XL": 78974,
          "S": 78971,
          "XXL": 78975
        }
      },
      {
        "name": "White",
        "swatch": "#efece2",
        "images": [
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73207/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73207/112433/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73207/98448/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73207/126095/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-5-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73207/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79169,
          "S": 73199,
          "M": 73203,
          "XL": 73211,
          "L": 73207,
          "XXL": 73215
        }
      },
      {
        "name": "Pepper",
        "swatch": "#575450",
        "images": [
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79048/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79048/112433/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79048/98448/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79048/126095/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-5-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79048/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79155,
          "L": 79048,
          "XL": 79049,
          "S": 79046,
          "M": 79047,
          "XXL": 79050
        }
      },
      {
        "name": "Granite",
        "swatch": "#9b9a94",
        "images": [
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73982/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73982/112433/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73982/98448/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73982/126095/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-5-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/73982/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79133,
          "L": 73982,
          "XL": 73989,
          "S": 73968,
          "M": 73975,
          "XXL": 73996
        }
      },
      {
        "name": "Mystic Blue",
        "swatch": "#5f7e93",
        "images": [
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79033/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79033/112433/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-1-front",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79033/98448/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-2",
          "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79033/126095/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=person-5-context"
        ],
        "image": "https://images-api.printify.com/mockup/6a27dd8575aae553c70ecf64/79033/98445/he-is-my-doctor-he-is-my-engineer-he-is-my-pastor-he-is-my-father-t-shirt.jpg?camera_label=front",
        "variants": {
          "3XL": 79151,
          "L": 79033,
          "S": 79031,
          "XL": 79034,
          "M": 79032,
          "XXL": 79035
        }
      }
    ]
  }
};

export interface ResolvedLine {
  name: string;
  priceCents: number;
  item: { product_id: string; variant_id: number; quantity: 1 };
}

/** Resolve { productId, color, size } to a priced line + Printify item. Throws on any miss. */
export function resolveLine(productId: string, color: string, size: Size): ResolvedLine {
  const product = CATALOG[productId];
  if (!product) throw new Error(`Unknown product: ${productId}`);
  const c = product.colors.find((x) => x.name === color);
  if (!c) throw new Error(`Unknown color ${color} for ${productId}`);
  const variant_id = c.variants[size];
  if (variant_id === undefined) throw new Error(`Unknown size ${size} for ${productId} / ${color}`);
  return {
    name: `${product.name} — ${color} / ${size}`,
    priceCents: product.priceCents,
    item: { product_id: product.printifyProductId, variant_id, quantity: 1 },
  };
}

export function listProducts(): Array<Product & { id: string }> {
  return Object.entries(CATALOG).map(([id, product]) => ({ id, ...product }));
}
