#!/usr/bin/env node
/**
 * Generates lib/catalog.ts from the live Printify shop — products x colors x sizes.
 * Curated metadata (names/blurbs/price/swatches/order) lives here; variant ids +
 * mockup images come from Printify. Re-run after Printify changes:
 *   node --env-file=.env.local scripts/gen-catalog.mjs
 */
import { writeFileSync } from "node:fs";

const TOKEN = process.env.PRINTIFY_API_TOKEN;
const SHOP = process.env.PRINTIFY_SHOP_ID;
if (!TOKEN || !SHOP) {
  console.error("Set PRINTIFY_API_TOKEN + PRINTIFY_SHOP_ID (use --env-file=.env.local)");
  process.exit(1);
}

const PRICE_CENTS = 3999;

// Curated product metadata, in display order.
const PRODUCTS = [
  {
    id: "6a27897a8f2246d09f0acb65",
    key: "knicks-in-four",
    name: "Knicks in Four Tee",
    tagline: "THE FINALS DROP",
    blurb:
      "The whole city is saying it, so we put it on a shirt. Heavyweight Comfort Colors cotton, shipped from New Jersey.",
  },
  {
    id: "6a27c36891cf9037720216b7",
    key: "better-than-brunson",
    name: "Better Than Brunson Tee",
    tagline: "CAPTAIN CLUTCH",
    blurb:
      "Everyone's better than Jalen Brunson — until it's time to be better than Jalen Brunson. For the doubters and the believers.",
  },
  {
    id: "6a27c372cf9078f4a3052270",
    key: "corgi-wrong",
    name: "Corgi's Gonna Be Wrong Tee",
    tagline: "FADE THE DOG",
    blurb:
      "The corgi's gonna be wrongggg. For everyone who fades the playoff pet picks and rides with New York.",
  },
];

// Swatch hexes + color display order.
const SWATCH = {
  White: "#efece2",
  Black: "#1c1c1c",
  Graphite: "#4f5356",
  Grey: "#b9bbbb",
  Granite: "#9b9a94",
  "Mystic Blue": "#5f7e93",
};
const COLOR_ORDER = ["White", "Black", "Graphite", "Grey", "Granite", "Mystic Blue"];
const SIZE_ALIAS = { "2XL": "XXL" };
const SIZE_ORDER = ["S", "M", "L", "XL", "XXL", "3XL", "4XL"];

async function getProduct(id) {
  const r = await fetch(`https://api.printify.com/v1/shops/${SHOP}/products/${id}.json`, {
    headers: { Authorization: `Bearer ${TOKEN}` },
  });
  if (!r.ok) throw new Error(`Printify ${r.status} for ${id}`);
  return r.json();
}

function buildColors(p) {
  const enabled = (p.variants || []).filter((v) => v.is_enabled);
  const byColor = {};
  for (const v of enabled) {
    const [color, rawSize] = (v.title || "").split(" / ");
    const size = SIZE_ALIAS[rawSize] || rawSize;
    (byColor[color] ??= {})[size] = v.id;
  }
  const colors = [];
  for (const color of COLOR_ORDER) {
    const variants = byColor[color];
    if (!variants) continue;
    const ids = new Set(Object.values(variants));
    const img =
      (p.images || []).find(
        (im) => im.position === "front" && (im.variant_ids || []).some((id) => ids.has(id)),
      ) || (p.images || []).find((im) => (im.variant_ids || []).some((id) => ids.has(id)));
    colors.push({
      name: color,
      swatch: SWATCH[color] || "#888888",
      image: img ? img.src : "",
      variants,
    });
  }
  return colors;
}

const catalog = {};
for (const meta of PRODUCTS) {
  const p = await getProduct(meta.id);
  catalog[meta.key] = {
    name: meta.name,
    priceCents: PRICE_CENTS,
    tagline: meta.tagline,
    blurb: meta.blurb,
    printifyProductId: meta.id,
    colors: buildColors(p),
  };
  const totalVariants = catalog[meta.key].colors.reduce(
    (n, c) => n + Object.keys(c.variants).length,
    0,
  );
  console.error(
    `  ${meta.key}: ${catalog[meta.key].colors.length} colors, ${totalVariants} variants`,
  );
}

const header = `// AUTO-GENERATED by scripts/gen-catalog.mjs from the Printify shop.
// Editable, but re-running the script overwrites it with fresh variant ids + mockups.
//
// SINGLE SOURCE OF TRUTH: products -> colors -> sizes -> Printify variant ids.

export type Size = ${SIZE_ORDER.map((s) => JSON.stringify(s)).join(" | ")};
export const SIZE_ORDER: Size[] = ${JSON.stringify(SIZE_ORDER)};

export interface ColorVariant {
  name: string;
  swatch: string; // hex for the picker
  image: string; // front mockup for this color
  variants: Partial<Record<Size, number>>; // size -> Printify variant id
}

export interface Product {
  name: string;
  priceCents: number;
  tagline?: string;
  blurb?: string;
  printifyProductId: string;
  colors: ColorVariant[];
}

export const CATALOG: Record<string, Product> = ${JSON.stringify(catalog, null, 2)};

export interface ResolvedLine {
  name: string;
  priceCents: number;
  item: { product_id: string; variant_id: number; quantity: 1 };
}

/** Resolve { productId, color, size } to a priced line + Printify item. Throws on any miss. */
export function resolveLine(productId: string, color: string, size: Size): ResolvedLine {
  const product = CATALOG[productId];
  if (!product) throw new Error(\`Unknown product: \${productId}\`);
  const c = product.colors.find((x) => x.name === color);
  if (!c) throw new Error(\`Unknown color \${color} for \${productId}\`);
  const variant_id = c.variants[size];
  if (variant_id === undefined) throw new Error(\`Unknown size \${size} for \${productId} / \${color}\`);
  return {
    name: \`\${product.name} — \${color} / \${size}\`,
    priceCents: product.priceCents,
    item: { product_id: product.printifyProductId, variant_id, quantity: 1 },
  };
}

export function listProducts(): Array<Product & { id: string }> {
  return Object.entries(CATALOG).map(([id, product]) => ({ id, ...product }));
}
`;

writeFileSync(new URL("../lib/catalog.ts", import.meta.url), header);
console.error("\nWrote lib/catalog.ts");
